ordering:
  home: ''
  hobbyists: ''
  business-owners: ''
  designers: ''
  developers: ''
  contact-us: ''
items:
  home:
    id: 101
    hash: ''
    dropdown_hide: ''
    width: auto
    class: ''
    icon: 'fa fa-home'
