name: 23
timestamp: 1445791775
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1443867711
positions:
  top-a: 'Top A'
  top-b: 'Top B'
  top-c: 'Top C'
  header: Header
  slideshow-a: 'Slideshow A'
  slideshow-b: 'Slideshow B'
  slideshow-c: 'Slideshow C'
  showcase-a: 'Showcase A'
  showcase-b: 'Showcase B'
  showcase-c: 'Showcase C'
  above-a: 'Above A'
  above-b: 'Above B'
  above-c: 'Above C'
  utility-a: 'Utility A'
  utility-b: 'Utility B'
  utility-c: 'Utility C'
  feature-a: 'Feature A'
  feature-b: 'Feature B'
  feature-c: 'Feature C'
  sidebar: Sidebar
  mainbar-a: 'Mainbar A'
  mainbar-b: 'Mainbar B'
  mainbar-c: 'Mainbar C'
  content-bottom: content-bottom
  aside: Aside
  expanded-a: 'Expanded A'
  expanded-b: 'Expanded B'
  expanded-c: 'Expanded C'
  extension-a: 'Extension A'
  extension-b: 'Extension B'
  extension-c: 'Extension C'
  bottom-a: 'Bottom A'
  bottom-b: 'Bottom B'
  bottom-c: 'Bottom C'
  footer-a: 'Footer A'
  footer-b: 'Footer B'
  footside-a: 'Footside A'
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  showcase: Showcase
  above: Above
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  footside: Footside
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-1427: 'System Messages'
  position:
    position-2135: 'Top A'
    position-8143: 'Top B'
    position-3919: 'Top C'
    position-9706: Header
    position-1202: 'Slideshow A'
    position-5427: 'Slideshow B'
    position-4660: 'Slideshow C'
    position-3850: 'Showcase A'
    position-6332: 'Showcase B'
    position-6237: 'Showcase C'
    position-7372: 'Above A'
    position-4420: 'Above B'
    position-1831: 'Above C'
    position-9151: 'Utility A'
    position-1473: 'Utility B'
    position-9890: 'Utility C'
    position-1587: 'Feature A'
    position-1893: 'Feature B'
    position-8987: 'Feature C'
    position-3647: Sidebar
    position-6291: 'Mainbar A'
    position-9530: 'Mainbar B'
    position-5622: 'Mainbar C'
    position-3535: content-bottom
    position-6106: Aside
    position-8089: 'Expanded A'
    position-4702: 'Expanded B'
    position-9906: 'Expanded C'
    position-8893: 'Extension A'
    position-6160: 'Extension B'
    position-2398: 'Extension C'
    position-7690: 'Bottom A'
    position-7569: 'Bottom B'
    position-9965: 'Bottom C'
    position-3500: 'Footer A'
    position-9306: 'Footer B'
    position-9385: 'Footside A'
  logo:
    logo-8319: Logo
    logo-1037: Logo
  menu:
    menu-9757: Menu
  custom:
    custom-7167: 'Off Canvas Toggle'
    custom-5639: Offcanvas
  branding:
    branding-7051: Branding
  social:
    social-2141: Social
  totop:
    totop-6550: 'To Top'
  mobile-menu:
    mobile-menu-7949: 'Mobile Menu'
  assets:
    assets-4858: 'Custom CSS / JS'
inherit: {  }
