name: _error
timestamp: 1546892057
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1443867711
positions:
  top-a: 'Top A'
  top-b: 'Top B'
  top-c: 'Top C'
  menu: 'Module Position'
  subMenu: 'Module Position'
  header: Header
  slideshow-a: 'Slideshow A'
  slideshow-b: 'Slideshow B'
  slideshow-c: 'Slideshow C'
  showcase-a: 'Showcase A'
  showcase-b: 'Showcase B'
  showcase-c: 'Showcase C'
  above-a: 'Above A'
  above-b: 'Above B'
  above-c: 'Above C'
  utility-a: 'Utility A'
  utility-b: 'Utility B'
  utility-c: 'Utility C'
  feature-a: 'Feature A'
  feature-b: 'Feature B'
  feature-c: 'Feature C'
  sidebar: Sidebar
  mainbar-a: 'Mainbar A'
  mainbar-b: 'Mainbar B'
  mainbar-c: 'Mainbar C'
  content-bottom: content-bottom
  aside: Aside
  expanded-a: 'Expanded A'
  expanded-b: 'Expanded B'
  expanded-c: 'Expanded C'
  extension-a: 'Extension A'
  extension-b: 'Extension B'
  extension-c: 'Extension C'
  bottom-a: 'Bottom A'
  bottom-b: 'Bottom B'
  bottom-c: 'Bottom C'
  footer-a: 'Footer A'
  footer-b: 'Footer B'
  footer-c: 'Footer C'
  footside-a: 'Footside A'
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  showcase: Showcase
  above: Above
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  footside: Footside
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Untitled
particles:
  messages:
    system-messages-9514: 'System Messages'
    system-messages-9973: 'System Messages'
  position:
    position-position-2116: 'Top A'
    position-position-8371: 'Top B'
    position-position-6531: 'Top C'
    position-position-2180: 'Module Position'
    position-position-6915: 'Module Position'
    position-position-2177: Header
    position-position-9017: 'Slideshow A'
    position-position-6967: 'Slideshow B'
    position-position-9840: 'Slideshow C'
    position-position-6881: 'Showcase A'
    position-position-6684: 'Showcase B'
    position-position-3365: 'Showcase C'
    position-position-3193: 'Above A'
    position-position-8062: 'Above B'
    position-position-2977: 'Above C'
    position-position-8118: 'Utility A'
    position-position-4065: 'Utility B'
    position-position-4328: 'Utility C'
    position-position-1607: 'Feature A'
    position-position-2558: 'Feature B'
    position-position-9540: 'Feature C'
    position-position-2184: Sidebar
    position-position-4825: 'Mainbar A'
    position-position-5721: 'Mainbar B'
    position-position-4844: 'Mainbar C'
    position-position-6998: content-bottom
    position-position-4654: Aside
    position-position-7316: 'Expanded A'
    position-position-8889: 'Expanded B'
    position-position-4141: 'Expanded C'
    position-position-7565: 'Extension A'
    position-position-6296: 'Extension B'
    position-position-9217: 'Extension C'
    position-position-7569: 'Bottom A'
    position-position-6443: 'Bottom B'
    position-position-6727: 'Bottom C'
    position-position-5459: 'Footer A'
    position-position-3444: 'Footer B'
    position-position-5334: 'Footer C'
    position-position-8868: 'Footside A'
  logo:
    logo-6125: Logo
    logo-3185: Logo
  spacer:
    spacer-7450: Spacer
  contentarray:
    contentarray-7349: 'Joomla Articles'
  totop:
    totop-9298: 'To Top'
  social:
    social-9547: Social
  mobile-menu:
    mobile-menu-4451: 'Mobile Menu'
  custom:
    custom-2990: Offcanvas
inherit:
  default:
    top: top
    system-messages-9514: system-messages-9644
    position-position-2116: position-position-2508
    position-position-8371: position-position-3685
    position-position-6531: position-position-1412
    slideshow: slideshow
    position-position-9017: position-position-1667
    position-position-6967: position-position-2642
    position-position-9840: position-position-2387
    expanded: expanded
    position-position-7316: position-position-9729
    position-position-8889: position-position-7933
    position-position-4141: position-position-7112
    extension: extension
    position-position-7565: position-position-7438
    position-position-6296: position-position-3451
    position-position-9217: position-position-8611
    bottom: bottom
    position-position-7569: position-position-8937
    position-position-6443: position-position-7625
    position-position-6727: position-position-9326
    footer: footer
    position-position-5459: position-position-3536
    position-position-3444: position-position-3459
    position-position-5334: position-position-4323
    footside: footside
    position-position-8868: position-position-3868
    copyright: copyright
    logo-3185: logo-8410
    totop-9298: totop-1077
    social-9547: social-4824
    offcanvas: offcanvas
    mobile-menu-4451: mobile-menu-3436
    custom-2990: custom-2373
  16:
    navigation: navigation
    logo-6125: logo-6140
    position-position-2180: position-position-9420
    spacer-7450: spacer-3994
    position-position-6915: position-position-3693
