version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1443867711
layout:
  /top/:
    -
      - system-messages-1500
    -
      - 'position-position-9827 33.3'
      - 'position-position-2102 33.3'
      - 'position-position-9822 33.3'
  /navigation/:
    -
      - 'logo-6140 35'
      - 'position-position-9420 65'
  /header/:
    -
      - position-position-2177
  /slideshow/:
    -
      - 'custom-5715 25'
      - 'position-position-1683 25'
      - 'position-position-6003 25'
      - 'position-position-2644 25'
  /showcase/:
    -
      - 'position-position-6881 33.3'
      - 'position-position-6684 33.3'
      - 'position-position-3365 33.3'
  /above/:
    -
      - 'position-position-3193 33.3'
      - 'position-position-8062 33.3'
      - 'position-position-2977 33.3'
  /utility/:
    -
      - 'position-position-8118 33.3'
      - 'position-position-4065 33.3'
      - 'position-position-4328 33.3'
  /feature/:
    -
      - 'position-position-1607 33.3'
      - 'position-position-2558 33.3'
      - 'position-position-9540 33.3'
  /container-3308/:
    -
      -
        'sidebar 13':
          -
            - position-position-2184
      -
        'mainbar 74':
          -
            - 'position-position-4825 33.3'
            - 'position-position-5721 33.3'
            - 'position-position-4844 33.3'
          -
            - system-content-8976
          -
            - position-position-6998
      -
        'aside 13':
          -
            - position-position-4654
  /expanded/:
    -
      - 'position-position-8590 33.3'
      - 'position-position-4866 33.3'
      - 'position-position-6842 33.3'
  /extension/:
    -
      - 'position-position-8027 33.3'
      - 'position-position-4727 33.3'
      - 'position-position-8212 33.3'
  /bottom/:
    -
      - 'position-position-5403 33.3'
      - 'position-position-3495 33.3'
      - 'position-position-8366 33.3'
  /container-4964/:
    -
      -
        'footer 75':
          -
            - 'position-position-7343 25'
            - 'position-position-8216 75'
      -
        'footside 25':
          -
            - position-position-7658
  /copyright/:
    -
      - 'logo-4833 24'
      - 'branding-7299 51'
      - 'social-8861 15'
      - 'totop-9648 10'
    -
      - position-module-2142
    -
      - position-module-3815
  offcanvas:
    -
      - mobile-menu-7861
    -
      - position-module-8670
structure:
  top:
    type: section
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: ''
  slideshow:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      class: 'box-darkgrey g-outer-box'
  above:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
  mainbar:
    type: section
  container-3308:
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  extension:
    type: section
    attributes:
      boxed: ''
  bottom:
    type: section
    attributes:
      boxed: ''
  footside:
    type: section
  container-4964:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
content:
  system-messages-1500:
    block:
      variations: 'nomarginall nopaddingall'
  position-position-9827:
    title: 'Top A'
    attributes:
      key: top-a
  position-position-2102:
    title: 'Top B'
    attributes:
      key: top-b
  position-position-9822:
    title: 'Top C'
    attributes:
      key: top-c
  logo-6140:
    attributes:
      rel: home
      alt: 'Joomla! London Logo'
      class: ''
  position-position-9420:
    title: 'Module Position'
    attributes:
      key: menu
  position-position-2177:
    title: Header
    attributes:
      key: header
  custom-5715:
    title: 'Off Canvas Toggle'
    attributes:
      enabled: 0
      html: "<div class=\"g-offcanvas-toggle\" data-offcanvas-toggle=\"\">\n  <i class=\"fa fa-fw fa-indent\"></i>\n</div>"
  position-position-1683:
    title: 'Slideshow A'
    attributes:
      key: slideshow-a
  position-position-6003:
    title: 'Slideshow B'
    attributes:
      key: slideshow-b
  position-position-2644:
    title: 'Slideshow C'
    attributes:
      key: slideshow-c
  position-position-6881:
    title: 'Showcase A'
    attributes:
      key: showcase-a
  position-position-6684:
    title: 'Showcase B'
    attributes:
      key: showcase-b
  position-position-3365:
    title: 'Showcase C'
    attributes:
      key: showcase-c
  position-position-3193:
    title: 'Above A'
    attributes:
      key: above-a
  position-position-8062:
    title: 'Above B'
    attributes:
      key: above-b
  position-position-2977:
    title: 'Above C'
    attributes:
      key: above-c
  position-position-8118:
    title: 'Utility A'
    attributes:
      key: utility-a
  position-position-4065:
    title: 'Utility B'
    attributes:
      key: utility-b
  position-position-4328:
    title: 'Utility C'
    attributes:
      key: utility-c
  position-position-1607:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-position-2558:
    title: 'Feature B'
    attributes:
      key: feature-b
  position-position-9540:
    title: 'Feature C'
    attributes:
      key: feature-c
  position-position-2184:
    title: Sidebar
    attributes:
      key: sidebar
  position-position-4825:
    title: 'Mainbar A'
    attributes:
      key: mainbar-a
  position-position-5721:
    title: 'Mainbar B'
    attributes:
      key: mainbar-b
  position-position-4844:
    title: 'Mainbar C'
    attributes:
      key: mainbar-c
  position-position-6998:
    title: content-bottom
    attributes:
      key: content-bottom
  position-position-4654:
    title: Aside
    attributes:
      key: aside
  position-position-8590:
    title: 'Expanded A'
    attributes:
      key: expanded-a
  position-position-4866:
    title: 'Expanded B'
    attributes:
      key: expanded-b
  position-position-6842:
    title: 'Expanded C'
    attributes:
      key: expanded-c
  position-position-8027:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-position-4727:
    title: 'Extension B'
    attributes:
      key: extension-b
  position-position-8212:
    title: 'Extension C'
    attributes:
      key: extension-c
  position-position-5403:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  position-position-3495:
    title: 'Bottom B'
    attributes:
      key: bottom-b
  position-position-8366:
    title: 'Bottom C'
    attributes:
      key: bottom-c
  position-position-7343:
    title: 'Footer A'
    attributes:
      key: footer-a
  position-position-8216:
    title: 'Footer B'
    attributes:
      key: footer-b
  position-position-7658:
    title: 'Footside A'
    attributes:
      key: footside-a
  totop-9648:
    title: 'To Top'
  position-module-2142:
    title: 'Module Instance'
    attributes:
      module_id: '216'
      key: module-instance
  position-module-3815:
    title: 'Module Instance'
    attributes:
      module_id: '220'
      key: module-instance
  mobile-menu-7861:
    title: 'Mobile Menu'
  position-module-8670:
    title: 'Module Instance'
    attributes:
      module_id: '208'
      key: module-instance
