name: '27'
timestamp: 1484587919
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1484586243
positions:
  top-a: 'Top A'
  top-b: 'Top B'
  top-c: 'Top C'
  header-a: 'Header A'
  header-b: 'Header B'
  header-c: 'Header C'
  slideshow-a: 'Slideshow A'
  slideshow-b: 'Slideshow B'
  slideshow-c: 'Slideshow C'
  showcase-a: 'Showcase A'
  showcase-b: 'Showcase B'
  showcase-c: 'Showcase C'
  above-a: 'Above A'
  above-b: 'Above B'
  above-c: 'Above C'
  utility-a: 'Utility A'
  utility-b: 'Utility B'
  utility-c: 'Utility C'
  feature-a: 'Feature A'
  feature-b: 'Feature B'
  feature-c: 'Feature C'
  sidebar: Sidebar
  mainbar-a: 'Mainbar A'
  mainbar-b: 'Mainbar B'
  mainbar-c: 'Mainbar C'
  aside: Aside
  expanded-a: 'Expanded A'
  expanded-b: 'Expanded B'
  expanded-c: 'Expanded C'
  extension-a: 'Extension A'
  extension-b: 'Extension B'
  extension-c: 'Extension C'
  bottom-a: 'Bottom A'
  bottom-b: 'Bottom B'
  bottom-c: 'Bottom C'
  footer-a: 'Footer A'
  footer-b: 'Footer B'
  footer-c: 'Footer C'
  footside-a: 'Footside A'
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  showcase: Showcase
  above: Above
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  footside: Footside
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-2493: 'System Messages'
  position:
    position-4778: 'Top A'
    position-3433: 'Top B'
    position-4688: 'Top C'
    position-1329: 'Header A'
    position-5828: 'Header B'
    position-2537: 'Header C'
    position-6468: 'Slideshow A'
    position-5904: 'Slideshow B'
    position-1339: 'Slideshow C'
    position-2859: 'Showcase A'
    position-9533: 'Showcase B'
    position-3384: 'Showcase C'
    position-2285: 'Above A'
    position-8658: 'Above B'
    position-8835: 'Above C'
    position-5710: 'Utility A'
    position-4199: 'Utility B'
    position-4662: 'Utility C'
    position-6200: 'Feature A'
    position-6970: 'Feature B'
    position-7557: 'Feature C'
    position-7897: Sidebar
    position-1450: 'Mainbar A'
    position-5049: 'Mainbar B'
    position-2208: 'Mainbar C'
    position-9620: Aside
    position-4593: 'Expanded A'
    position-7584: 'Expanded B'
    position-6470: 'Expanded C'
    position-4028: 'Extension A'
    position-9621: 'Extension B'
    position-5703: 'Extension C'
    position-6153: 'Bottom A'
    position-5732: 'Bottom B'
    position-7269: 'Bottom C'
    position-7413: 'Footer A'
    position-2266: 'Footer B'
    position-2009: 'Footer C'
    position-9475: 'Footside A'
  logo:
    logo-5712: Logo
    logo-1178: Logo
  menu:
    menu-2750: Menu
  custom:
    custom-8804: 'Off Canvas Toggle'
    custom-8235: Offcanvas
  social:
    social-6874: Social
    social-7379: Social
  content:
    system-content-1143: 'Page Content'
  totop:
    totop-6789: 'To Top'
  mobile-menu:
    mobile-menu-3082: 'Mobile Menu'
inherit: {  }
