version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1484586243
layout:
  /top/:
    -
      - system-messages-2493
    -
      - 'position-4778 33.3333'
      - 'position-3433 33.3333'
      - 'position-4688 33.3333'
  /navigation/:
    -
      - 'logo-5712 20'
      - 'menu-2750 55'
      - 'custom-8804 5'
      - 'social-6874 20'
  /header/:
    -
      - 'position-1329 33.3333'
      - 'position-5828 33.3333'
      - 'position-2537 33.3333'
  /slideshow/:
    -
      - 'position-6468 33.3333'
      - 'position-5904 33.3333'
      - 'position-1339 33.3333'
  /showcase/:
    -
      - 'position-2859 33.3333'
      - 'position-9533 33.3333'
      - 'position-3384 33.3333'
  /above/:
    -
      - 'position-2285 33.3333'
      - 'position-8658 33.3333'
      - 'position-8835 33.3333'
  /utility/:
    -
      - 'position-5710 33.3333'
      - 'position-4199 33.3333'
      - 'position-4662 33.3333'
  /feature/:
    -
      - 'position-6200 33.3333'
      - 'position-6970 33.3333'
      - 'position-7557 33.3333'
  /container-9729/:
    -
      -
        'sidebar 20':
          -
            - position-7897
      -
        'mainbar 60':
          -
            - 'position-1450 33.3333'
            - 'position-5049 33.3333999999'
            - 'position-2208 33.3333'
          -
            - system-content-1143
      -
        'aside 20':
          -
            - position-9620
  /expanded/:
    -
      - 'position-4593 33.3333'
      - 'position-7584 33.3333'
      - 'position-6470 33.3333'
  /extension/:
    -
      - 'position-4028 33.3333'
      - 'position-9621 33.3334'
      - 'position-5703 33.3333'
  /bottom/:
    -
      - 'position-6153 33.3333'
      - 'position-5732 33.3333'
      - 'position-7269 33.3333'
  /container-5327/:
    -
      -
        'footer 75':
          -
            - 'position-7413 33.3333'
            - 'position-2266 33.3333'
            - 'position-2009 33.3333'
      -
        'footside 25':
          -
            - position-9475
  /copyright/:
    -
      - 'logo-1178 33.3333'
      - 'totop-6789 33.3333'
      - 'social-7379 33.3333'
  offcanvas:
    -
      - mobile-menu-3082
    -
      - custom-8235
structure:
  top:
    type: section
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
      class: ''
  header:
    attributes:
      boxed: ''
  slideshow:
    type: section
    attributes:
      boxed: ''
  showcase:
    type: section
    attributes:
      boxed: ''
      class: 'box-darkgrey g-outer-box'
  above:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
  feature:
    type: section
    attributes:
      boxed: ''
  sidebar:
    type: section
  mainbar:
    type: section
  container-9729:
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  extension:
    type: section
    attributes:
      boxed: ''
  bottom:
    type: section
    attributes:
      boxed: ''
  footside:
    type: section
  container-5327:
    attributes:
      boxed: ''
  copyright:
    type: section
    attributes:
      boxed: ''
content:
  system-messages-2493:
    layout: false
    block:
      variations: 'nomarginall nopaddingall'
  position-4778:
    title: 'Top A'
    attributes:
      key: top-a
    layout: false
  position-3433:
    title: 'Top B'
    attributes:
      key: top-b
    layout: false
  position-4688:
    title: 'Top C'
    attributes:
      key: top-c
    layout: false
  logo-5712:
    attributes:
      rel: home
      alt: joomlalondon
    layout: false
  menu-2750:
    layout: false
  custom-8804:
    title: 'Off Canvas Toggle'
    attributes:
      html: "<div class=\"g-offcanvas-toggle\" data-offcanvas-toggle=\"\">\n  <i class=\"fa fa-fw fa-indent\"></i>\n</div>"
    layout: false
  social-6874:
    layout: false
  position-1329:
    title: 'Header A'
    attributes:
      key: header-a
    layout: false
  position-5828:
    title: 'Header B'
    attributes:
      key: header-b
    layout: false
  position-2537:
    title: 'Header C'
    attributes:
      key: header-c
    layout: false
  position-6468:
    title: 'Slideshow A'
    attributes:
      key: slideshow-a
    layout: false
  position-5904:
    title: 'Slideshow B'
    attributes:
      key: slideshow-b
    layout: false
  position-1339:
    title: 'Slideshow C'
    attributes:
      key: slideshow-c
    layout: false
  position-2859:
    title: 'Showcase A'
    attributes:
      key: showcase-a
    layout: false
  position-9533:
    title: 'Showcase B'
    attributes:
      key: showcase-b
    layout: false
  position-3384:
    title: 'Showcase C'
    attributes:
      key: showcase-c
    layout: false
  position-2285:
    title: 'Above A'
    attributes:
      key: above-a
    layout: false
  position-8658:
    title: 'Above B'
    attributes:
      key: above-b
    layout: false
  position-8835:
    title: 'Above C'
    attributes:
      key: above-c
    layout: false
  position-5710:
    title: 'Utility A'
    attributes:
      key: utility-a
    layout: false
  position-4199:
    title: 'Utility B'
    attributes:
      key: utility-b
    layout: false
  position-4662:
    title: 'Utility C'
    attributes:
      key: utility-c
    layout: false
  position-6200:
    title: 'Feature A'
    attributes:
      key: feature-a
    layout: false
  position-6970:
    title: 'Feature B'
    attributes:
      key: feature-b
    layout: false
  position-7557:
    title: 'Feature C'
    attributes:
      key: feature-c
    layout: false
  position-7897:
    title: Sidebar
    attributes:
      key: sidebar
    layout: false
  position-1450:
    title: 'Mainbar A'
    attributes:
      key: mainbar-a
    layout: false
  position-5049:
    title: 'Mainbar B'
    attributes:
      key: mainbar-b
    layout: false
  position-2208:
    title: 'Mainbar C'
    attributes:
      key: mainbar-c
    layout: false
  system-content-1143:
    layout: false
  position-9620:
    title: Aside
    attributes:
      key: aside
    layout: false
  position-4593:
    title: 'Expanded A'
    attributes:
      key: expanded-a
    layout: false
  position-7584:
    title: 'Expanded B'
    attributes:
      key: expanded-b
    layout: false
  position-6470:
    title: 'Expanded C'
    attributes:
      key: expanded-c
    layout: false
  position-4028:
    title: 'Extension A'
    attributes:
      key: extension-a
    layout: false
  position-9621:
    title: 'Extension B'
    attributes:
      key: extension-b
    layout: false
  position-5703:
    title: 'Extension C'
    attributes:
      key: extension-c
    layout: false
  position-6153:
    title: 'Bottom A'
    attributes:
      key: bottom-a
    layout: false
  position-5732:
    title: 'Bottom B'
    attributes:
      key: bottom-b
    layout: false
  position-7269:
    title: 'Bottom C'
    attributes:
      key: bottom-c
    layout: false
  position-7413:
    title: 'Footer A'
    attributes:
      key: footer-a
    layout: false
  position-2266:
    title: 'Footer B'
    attributes:
      key: footer-b
    layout: false
  position-2009:
    title: 'Footer C'
    attributes:
      key: footer-c
    layout: false
  position-9475:
    title: 'Footside A'
    attributes:
      key: footside-a
    layout: false
  logo-1178:
    attributes:
      rel: home
      image: 'gantry-media://logo/logo-footer.png'
      alt: Joomlalondon
      class: g-footer-logo
    layout: false
  totop-6789:
    title: 'To Top'
    layout: false
  social-7379:
    attributes:
      items:
        -
          icon: 'fa fa-twitter fa-fw'
          text: ''
          link: 'http://twitter.com/rockettheme'
          name: Twitter
        -
          icon: 'fa fa-facebook fa-fw'
          text: ''
          link: 'http://facebook.com/rockettheme'
          name: Facebook
        -
          icon: 'fa fa-google fa-fw'
          text: ''
          link: 'https://plus.google.com/+rockettheme/about'
          name: Google
        -
          icon: 'fa fa-rss fa-fw'
          text: ''
          link: 'http://www.rockettheme.com/product-updates?rss'
          name: RSS
    layout: false
  mobile-menu-3082:
    title: 'Mobile Menu'
    layout: false
  custom-8235:
    title: Offcanvas
    attributes:
      html: "<div class=\"g-offcanvas-toggle\" data-offcanvas-toggle=\"\">\n  <i class=\"fa fa-fw fa-remove\"></i>\n</div>\n\n<h4 class=\"g-subpromo nomarginbottom\"><a href=\"#\">Creativity</a></h4>\n<h4 class=\"g-subpromo nomarginbottom\"><a href=\"#\">Innovation</a></h4>\n<h4 class=\"g-subpromo nomarginbottom\"><a href=\"#\">Originality</a></h4>\n<h4 class=\"g-subpromo nomarginbottom\"><a href=\"#\">Imagination</a></h4>\n\n<div class=\"largemarginall largepaddingall\">&nbsp;</div>\n\n<hr />\n\n<h2 class=\"g-promo\">Joomlalondon</h2>\n\n<p>Joomlalondon is an excellent design with a fresh approach for the ever-changing Web. Integrated with Gantry 5, it is infinitely customizable, incredibly powerful, and remarkably simple.</p>\n\n<a href=\"http://www.rockettheme.com/joomla/templates/joomlalondon\" class=\"button button-3\"><i class=\"fa fa-fw fa-cloud-download\"></i> Download</a>"
    layout: false
