version: 2
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1443867711
layout:
  /body/:
    -
      - system-messages-5153
    -
      - system-content-8604
  offcanvas: {  }
structure:
  body:
    type: section
    attributes:
      boxed: 1
content:
  system-messages-5153:
    layout: false
    block:
      variations: 'nomarginall nopaddingall'
  system-content-8604:
    layout: false
