name: _offline
timestamp: 1495041535
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1443867711
positions: {  }
sections:
  top: Top
  navigation: Navigation
  slideshow: Slideshow
  showcase: Showcase
  above: Above
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  footside: Footside
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  messages:
    system-messages-1405: 'System Messages'
  logo:
    logo-5346: Logo
    logo-4418: Logo
  spacer:
    spacer-9944: Spacer
    spacer-5015: Spacer
    spacer-8433: Spacer
  custom:
    custom-1763: 'Coming Soon'
    custom-2601: 'Have Something to Tell Us?'
  content:
    system-content-8263: 'Page Content'
  totop:
    totop-7796: 'To Top'
  social:
    social-9464: Social
inherit: {  }
