atoms:
  -
    type: assets
    title: 'Custom CSS / JS'
    attributes:
      enabled: '1'
      css: {  }
      javascript:
        - { location: 'gantry-assets://custom/assets/js/date-en-GB.js', inline: '', in_footer: '0', extra: {  }, name: Date-en-gb }
        - { location: '', inline: "document.getElementById(\"next3rdTuesday\").innerHTML = next3rdTuesday();\n\nfunction next3rdTuesday() {\n\tvar next = new Date.today().moveToNthOccurrence(2, 3);\n\tvar time = new Date.today().setTimeToNow();\n\tif (time.isAfter(next.addHours(18).addMinutes(59))) {\n\t\t\tnext = Date.today().addMonths(1).moveToNthOccurrence(2, 3);\n\t}\n\t\tvar dateText;\n\t\tif (time.same().day(next)) {\n\t\t\tdateText = 'Today';\n\t\t} else if (time.addDays(1).same().day(next)) {\n\t\t\tdateText = 'Tommorrow';\n} else {\n\t\t\tdateText = next.toString('dddd dS MMMM');\n\t\t}\n\t\treturn dateText;\n}", in_footer: '1', extra: {  }, name: Next3rdTuesday }
